## Importing Libraries

In [1]:
import numpy as np

### 1.Find the sum of all numbers from 1 to 500

In [2]:
np.sum(np.arange(501))
#np.sum([i for i in range (501)])

125250

### 2. Find the sum of squares of all numbers from 1 to 10

In [3]:
np.sum(np.square(np.arange(11)))
#np.sum([np.square(i) for i in range(11)])

385

### 3. Find the median of squares of all numbers from 1 to 100

In [4]:
np.median(np.square(np.arange(101)))
#np.median([np.square(i) for i in range(101)])

2500.0

### 4. Find the standard deviation of squares of all numbers from 1 to 100

In [5]:
np.std(np.square(np.arange(101)))
#np.std([np.square(i) for i in range(101)])

3012.943743251772

### 5. Write a function to calculate the standard deviation of an array without using _np.std_ .
$ \sigma=\sqrt{\frac{1}{N}\sum_{i=1}^{N}(x_{i}-\mu)^2} $

In [6]:
import math

def without_npstd(N):
#     sigma = 0
    mean = np.mean(np.arange(1, N + 1))
    sigma = np.sum([np.square(i - mean) for i in range(1,N + 1)])
#     for i in range(1, N + 1):
#         sigma = np.sum(np.square(i - mean))
    sq_root = sigma / N
    variance = math.sqrt(sq_root)
    return variance

In [7]:
print(without_npstd(100))

28.86607004772212


In [8]:
#Checking correctnes of my function
without_npstd(100) == np.std(np.arange(1, 101))

True

### 6. Read  <a href="https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy">this</a>  numpy article on broadcasting, and briefly explain broadcasting in your own words <br>
#### Answer:
Array broadcasting allows performing arithmetical operations of numpy arrays even with non-compatibles shapes. For instance, if we try to add a number $a$ to the vector or array $v$, the number $a$ is broadcasted to the according shape of the vector $v$. <br> 
<br>
**Let's define these vector and number,** <br>
```import numpy as np``` <br>
```v = array([1.0, 2.0, 3.0])``` <br>
```a = 10``` <br>
When we try to perform ```v + a```, it gives us output ```array([11, 12, 13])```, because number $a$ is extended or **_broadcasted_** to an array $[10, 10, 10]$

### 7. Let x = np.ones((10, 20, 30)). What is the shape of x.sum(axis=0), x.sum(axis=1) and x.sum(axis=2)?

In [9]:
x = np.ones((10, 20, 30))

In [10]:
np.shape(x.sum(axis = 0))

(20, 30)

In [11]:
np.shape(x.sum(axis = 1))

(10, 30)

In [12]:
np.shape(x.sum(axis = 2))

(10, 20)

### 8. Suppose y.shape is (a, b, c, ..., z). What is the shape of y.sum(axis=i) for _0 ≤ i < 26_ ?
__The shape of y.sum(axis=i) consist of all the dimenisons(letters) of the array _without_ _$i^{th}$_ dimension(letter) of the array. For instance, ```np.shape(y.sum(axis=0))``` will give us output of ```(b,c,d,..., z)```__

### 9. Suppose x is an array of shape (100, 10). Each row represents a student and each column represents an exam. Write numpy expressions that represent:

In [13]:
student_grade = np.random.uniform(50,101, [100,10]) #Randomly seeds numbers from 50 to 100 to our 2-dimensional array

>### a. The average grade of each student

In [14]:
np.average(student_grade, axis=1)

array([71.35591016, 75.37122751, 72.66476543, 77.76493666, 77.27336662,
       79.92758512, 85.80095102, 71.98578994, 72.36731305, 72.39670841,
       67.64562218, 76.60404715, 69.35840213, 88.42776554, 85.19995079,
       78.68037643, 78.91009201, 72.88669076, 76.72858089, 79.27127988,
       81.57877629, 72.68804186, 73.14549141, 73.1616749 , 85.47264176,
       74.0120459 , 70.95720846, 74.33869622, 70.17059373, 64.13272305,
       67.63874918, 76.93723423, 75.08649899, 76.84618891, 75.14770098,
       80.33263612, 66.59626354, 80.00975771, 84.31439401, 75.62621224,
       74.34022626, 72.3797977 , 76.67724998, 69.94401237, 75.45713862,
       72.84271898, 75.30329448, 78.11507296, 83.47565077, 81.57459821,
       77.05791787, 80.65979252, 76.52100494, 73.89826961, 71.53237421,
       75.46452125, 69.75496296, 82.01852626, 73.00739863, 77.64746764,
       70.029463  , 82.41773358, 72.17864589, 71.18132962, 76.87724041,
       74.46739181, 81.31753352, 78.85514904, 78.34909492, 70.66

>### b. The average grade in each exam

In [15]:
np.mean(student_grade, axis=0)

array([74.99965984, 77.09346843, 75.36480933, 75.32665091, 76.63599823,
       77.66429234, 76.61848684, 75.84680571, 75.06857537, 75.09163566])

### 10. The following table describes the grades of several students in several assignments in a course, as well as their final grade in the course. _Find the weight of each assignment in the final grade (some grades are rounded)_.

<img src="./assets/images/exercise10_table.png">

In [16]:
student_1 = np.array([89, 93, 83, 88])
student_2 = np.array([100, 86, 78, 86])
student_3 = np.array([97, 90, 88, 91])
student_4 = np.array([83, 99, 100, 96])
student_5 = np.array([100, 81, 75, 83])

data = np.array([student_1, student_2, student_3, student_4, student_5])
X = data[:,:-1] #till index -1
y = data[:, -1] #only index -1

In [17]:
X

array([[ 89,  93,  83],
       [100,  86,  78],
       [ 97,  90,  88],
       [ 83,  99, 100],
       [100,  81,  75]])

In [18]:
y

array([88, 86, 91, 96, 83])

If we consider that is is an overdetermined system <br>
$\sum_{j=1}^{p}= X_{ij}\beta_{j} = y_{i}, (i = 1, 2, ..., n)$ <br>
with $n$ linear equations $p$ unknown coefficients(in our case, there are 3 unknown coefficients) $\beta_{1}, \beta_{2}, ..., \beta_{p}$. <br>
We can find the coefficient by using the property below: <br>
$(X^{T}X)\hat{\beta} = X^{T}y$, <br>
where $(X^{T}X)$ is **_Gram matrix_** and the matrix $X^{T}y$ is knows as the **_moment matrix_**, and $\hat{\beta}$ is the coefficient vector that we have to find <br>
<br>
$\hat{\beta} = (X^{T}X)^{-1}X^{T}y$ - solution to our exercise

In [19]:
# beta = np.linalg.inv(X.T @ X) @ X.T @ y
beta = np.asmatrix((X.T @ X)).I @ X.T @ y #or np.matrix().I
# beta = np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T, X)), X.T), y)

In [20]:
print(f'Weights of each assignment: {np.array(beta)}')

Weights of each assignment: [[0.23083893 0.33911109 0.43272626]]
