In [1]:
import numpy as np

In [4]:
X = np.array([[ 89,  93,  83],
              [100,  86,  78],
              [ 97,  90,  88],
              [ 83,  99, 100],
              [100,  81,  75]])

In [5]:
### 5 methods of implementing matrix transpose 

# Method 1
# result = np.zeros((3, 5), dtype = np.int32)
# print(result)
result = np.zeros((X.shape[1], X.shape[0]), dtype=np.int32)
# Iterate through rows
for i in range(len(X)):
   #Iterate through columns
    for j in range(len(X[0])):
        result[j][i] = X[i][j]
print(result)

[[ 89 100  97  83 100]
 [ 93  86  90  99  81]
 [ 83  78  88 100  75]]


In [6]:
#Method 2
result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
for r in result:
    print(r)

[89, 100, 97, 83, 100]
[93, 86, 90, 99, 81]
[83, 78, 88, 100, 75]


In [7]:
#Method 3
result_1 = map(list, zip(*X))
result_2 = map(list, zip(X))

print(result_1)
print(result_2)

for r in result_1:
    print(r)
print()
for r in result_2:
    print(r)

[89, 100, 97, 83, 100]
[93, 86, 90, 99, 81]
[83, 78, 88, 100, 75]

[array([89, 93, 83])]
[array([100,  86,  78])]
[array([97, 90, 88])]
[array([ 83,  99, 100])]
[array([100,  81,  75])]


In [8]:
# Method 4
print(np.transpose(X,(1,0)))

[[ 89 100  97  83 100]
 [ 93  86  90  99  81]
 [ 83  78  88 100  75]]


In [9]:
# Method 5
X.T

array([[ 89, 100,  97,  83, 100],
       [ 93,  86,  90,  99,  81],
       [ 83,  78,  88, 100,  75]])